### ISSUE TITLE
[Suggestion] Add new block type: MESSAGE

### ISSUE THREAD

**Issue by FaultyFunctions** [JadedMC/CommandBlockerPro#1]
Hello! So I'm currently using the plugin in a unique way. We don't have a `/spawn` command but we have teleport scrolls instead. So I'm making it so when a user types `/spawn` it'll display a message linking to our wiki about teleport scrolls. However I thought it would be nice to official support this and had a few ideas on how this would work.

## MESSAGE type
So this would basically SHOW the specified command in the tab complete list, but it would still block and instead send a customized message to the user. Currently you can use BLACKLIST as a workaround, but you'll get a unknown command error in the tab completion message. This type would essentially be the opposite of the `HIDE` type, instead of hiding and not blocking, it would block and not hide (or add a tab complete a custom command that didn't exist in the first place).

This was me on SpigotMC btw!
![image](https://github.com/JadedMC/CommandBlockerPro/assets/6508045/f2cae51e-840c-4c14-a130-a3985988099d)

**Comment by firewolf8385** [comment]
Sorry it has taken so long to get to this, I've finally found a way to accomplish this. This feature will be in the next update, which I expect to release fairly soon, in case you are still using the plugin.
